### ISSUE TITLE
Allow unauthenticated SMTP

### ISSUE THREAD

**Issue by 0x2142** [david-kalmakoff/gotify-smtp-emailer#1]
Hello there & thank you for publishing this plugin for Gotify!

I would like to use this to send out email via a local open SMTP relay, however currently the plugin requires authentication. I can put in some fake credentials when I configure the plugin, but since [smtp.PlainAuth](https://pkg.go.dev/net/smtp#PlainAuth) requires TLS it generates the following error: `smtp send error: could not send email: unencrypted connection`

If possible, would you be willing to add an option for no authentication? Happy to submit a PR for this if you like.

Thank you!

**Comment by david-kalmakoff** [comment]
No problem, thank you for your interest in it.

I agree that it would be helpful to have an `Insecure` option for the SMTP connection. I ran into a similar issue when testing the plugin locally.

I can make an update some time by Tuesday. If you are excited to make the change, feel free, I am also happy to make the update.

Thank you

**Comment by david-kalmakoff** [comment]
Some time came up and I got excited about touching this project again. I added an `Insecure` option in the SMTP configuration to allow for an unencrypted connection.

This update has been included in the v0.2.0 release.

Please let me know if this fixed your problem or not. 

Thank you

**Comment by 0x2142** [comment]
Hi there - thanks for the quick response! So it looks like the new `insecure` option is still using [smtp.CRAMMD5Auth](https://github.com/david-kalmakoff/gotify-smtp-emailer/blob/c0e6fd09b9aa41de20f04ed9cab614c0b0957f17/smtp.go#L75), which for me generates the following error when sending messages: `smtp send error: could not send email: 504 5.7.4 Unsupported authentication mechanism`

I am able to get the plugin working by setting `nil` for `Auth` on [this line](https://github.com/david-kalmakoff/gotify-smtp-emailer/blob/c0e6fd09b9aa41de20f04ed9cab614c0b0957f17/smtp.go#L79):
`err := smtp.SendMail(uri, nil, s.FromEmail, s.ToEmails, []byte(content))`

**Comment by david-kalmakoff** [comment]
Hi, no problem. Thanks for the patience with sorting this out. I made it so you can no configure the plugin without an SMTP password. When there is no password entered it attempts to send the email with no auth. It should now work if you just remove the `Password` from your configuration.

**Comment by 0x2142** [comment]
Works great now. Thank you so much!
